---
- name: Install Node Exporter
  hosts: all
  become: true

  tasks:

    - name: Install Node Exporter
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present
        update_cache: true

    - name: Start Node Exporter
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        state: started
        enabled: true