server {
    listen 80;
    server_name monitoring-rezaarishadilah.studentdumbways.my.id;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name monitoring-rezaarishadilah.studentdumbways.my.id;

    ssl_certificate /etc/letsencrypt/live/studentdumbways.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studentdumbways.my.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


server {
    listen 80;
    server_name prom-rezaarishadilah.studentdumbways.my.id;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name prom-rezaarishadilah.studentdumbways.my.id;

    ssl_certificate /etc/letsencrypt/live/studentdumbways.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studentdumbways.my.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:9090;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


server {
    listen 80;
    server_name exporter-rezaarishadilah.studentdumbways.my.id;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name exporter-rezaarishadilah.studentdumbways.my.id;

    ssl_certificate /etc/letsencrypt/live/studentdumbways.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studentdumbways.my.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:9100;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}